### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by hackmoonlight** [cea-sec/Sibyl#16]
i tried to work with sibyle , i run this command but it generates this error . 

`python2 find.py  /home/younes/Bureau/a.out  ABIStdCall_x86_32  0x400410`

```
Guessed architecture: x86_64
Process Process-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "find.py", line 66, in do_test
    possible_funcs = tl.run(address, timeout_seconds=timeout)
  File "/home/younes/Bureau/Sibyl/sibyl/testlauncher.py", line 181, in run
    self.launch_tests(test, address, *args, **kwargs)
  File "/home/younes/Bureau/Sibyl/sibyl/testlauncher.py", line 169, in launch_tests
    status = test.tests.execute(launch_test)
  File "/home/younes/Bureau/Sibyl/sibyl/test/test.py", line 236, in execute
    if not callback(init, check):
  File "/home/younes/Bureau/Sibyl/sibyl/testlauncher.py", line 144, in launch_test
    self.abi.prepare_call(ret_addr=0x1337beef)
  File "/home/younes/Bureau/Sibyl/sibyl/abi/abi.py", line 83, in prepare_call
    self.vm_push(element)
  File "/home/younes/Bureau/Sibyl/sibyl/abi/x86.py", line 33, in vm_push
    self.jitter.push_uint32_t(element)
AttributeError: jitter_x86_64 instance has no attribute 'push_uint32_t'
```

**Comment by commial** [comment]
It seems that you are using a x86 32bits ABI (`ABIStdCall_x86_32`) on a 64bits binary

Please have a try with a x86_64 ABI. If the architecture detection is not correct, you can force it with the corresponding option.

**Comment by hackmoonlight** [comment]
I think he did not find the name of this function 
`No candidate found for 0x0804841b`

**Comment by commial** [comment]
Without any more detail, it will be hard for me to debug it. What was the function you expected it to found ? Is this function implemented in Sibyl signatures ?

**Comment by commial** [comment]
I plan to add a `debug` action to display why a given method has not been recognized (or at least some hint). It seems to be useful when one is persuaded (after manual analysis) that a function is XXX, and Sibyl disagree. In some case, this is due to corner case in the function, missed by the manual analysis.

For now, as I don't have any update, I'm closing the issue. Do not hesitate to re-open if necessary.
